apiVersion: v1
kind: ConfigMap
metadata:
  name: userimage-api-config
  namespace: default
  labels:
    app: userimage-api
data:
  appsettings.json: |
    {
      "AppConfigUrl": "https://cfg-smartoffice-001.azconfig.io",
      "BaseAddress": "http://userimage-api-clusterip-srv:8080",
      "StoragePath": "/app/storage",        
      "Serilog": {
          "MinimumLevel": {
              "Default": "Debug",
              "Override": {
                  "Microsoft": "Error",
                  "System": "Error"
              }
          },
          "WriteTo": [
              {
                  "Args": {
                      "OutputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss} [{Level:u3}] {Message:lj}{NewLine}{Exception}"
                  },
                  "Name": "Console"
              }
          ]
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userimage-api-depl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userimage-api
  template:
    metadata:
      labels:
        app: userimage-api
    spec:
      containers:
        - name: userimage-api
          image: domih/mcce-smart-office-userimage-api:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          volumeMounts:
            # - name: smart-office-pv
            #   mountPath: /smartoffice
            - name: userimage-api-config
              mountPath: /app/appsettings.json
              subPath: appsettings.json
      volumes:
        - name: smart-office-pv
          hostPath:
            path: /run/desktop/mnt/host/c/temp/smartoffice/userimages
            type: Directory
        - name: userimage-api-config
          configMap:
            name: userimage-api-config
---
apiVersion: v1
kind: Service
metadata:
  name: userimage-api-clusterip-srv
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: userimage-api
  ports:
    - name: userimage-api
      protocol: TCP
      port: 80
      targetPort: 8080
