apiVersion: v1
kind: ConfigMap
metadata:
  name: userimage-api-config
  namespace: default
  labels:
    app: userimage-api
data:
  appsettings.json: |
    {
      "AppConfigUrl": "https://cfg-smartoffice-001.azconfig.io",
      "BaseAddress": "http://userimage-api-clusterip-srv:8080",
      "StoragePath": "/mnt/userimages",        
      "Serilog": {
          "MinimumLevel": {
              "Default": "Debug",
              "Override": {
                  "Microsoft": "Error",
                  "System": "Error"
              }
          },
          "WriteTo": [
              {
                  "Args": {
                      "OutputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss} [{Level:u3}] {Message:lj}{NewLine}{Exception}"
                  },
                  "Name": "Console"
              }
          ]
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userimage-api-depl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userimage-api
  template:
    metadata:
      labels:
        app: userimage-api
    spec:
      containers:
        - name: userimage-api
          image: domih/mcce-smart-office-userimage-api:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          volumeMounts:
            - name: userimage-storage
              mountPath: /mnt/userimages
            - name: userimage-api-config
              mountPath: /app/appsettings.json
              subPath: appsettings.json
      volumes:
        - name: userimage-storage
          csi:
            driver: file.csi.azure.com
            readOnly: false
            volumeAttributes:
              secretName: azure-secret
              shareName: userimages-file-share
              mountOptions: "dir_mode=0777,file_mode=0777,cache=strict,actimeo=30,nosharesock" # optional
          # persistentVolumeClaim:
          #   claimName: userimage-pv-claim
        - name: userimage-api-config
          configMap:
            name: userimage-api-config
---
apiVersion: v1
kind: Service
metadata:
  name: userimage-api-clusterip-srv
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: userimage-api
  ports:
    - name: userimage-api
      protocol: TCP
      port: 80
      targetPort: 8080
