apiVersion: v1
kind: ConfigMap
metadata:
  name: workspace-api-config
  namespace: default
  labels:
    app: workspace-api
data:
  appsettings.json: |
    {
      "BaseAddress": "http://workspace-api-clusterip-srv:8080",
      "ConnectionString" :"Data Source=/app/storage/workspaces.db",
      "Serilog": {
          "MinimumLevel": {
              "Default": "Debug",
              "Override": {
                  "Microsoft": "Debug",
                  "System": "Debug"
              }
          },
          "WriteTo": [
              {
                  "Args": {
                      "OutputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss} [{Level:u3}] {Message:lj}{NewLine}{Exception}"
                  },
                  "Name": "Console"
              }
          ]
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-api-depl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workspace-api
  template:
    metadata:
      labels:
        app: workspace-api
    spec:
      containers:
        - name: workspace-api
          image: domih/mcce-smart-office-workspace-api:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          volumeMounts:
            - name: workspace-api-config
              mountPath: /app/appsettings.json
              subPath: appsettings.json
      volumes:
        - name: workspace-api-config
          configMap:
            name: workspace-api-config
---
apiVersion: v1
kind: Service
metadata:
  name: workspace-api-clusterip-srv
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: workspace-api
  ports:
    - name: workspace-api
      protocol: TCP
      port: 80
      targetPort: 8080
