apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: default
data:
  mosquitto.conf: |
    listener 1883 0.0.0.0
    allow_anonymous false    
    password_file /mosquitto/config/password.txt
    persistence false
    log_dest stdout
