apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-password
  namespace: default
data:
  password.txt: |
    admin:$7$101$Bxku3aSKlC9CIHAx$6C84+QJ1RyqbYB5wLrBAC7H3Ll48YOAAXjE/IFJ1SHPgUbuxYyFj9HomBtkRU0oMvZNb1UpLSWWnWuyoYtyGew==
    iot:$7$101$K2oUFEe2uPVwnFJV$+kGE8WWoteMWfv+sOvz6GPy07x4kJSZOhOGp6mRin3Do7k/lkePmvWYrJjl5YFP1YA4xM/+JmbACr+XIbuHoRQ==
