AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploys the MCCE22 Smart Office AWS lambda functions

Resources: 

  Mcce22SmartOfficeUsersLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../Mcce22.SmartOffice.Users/
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /userapi/{proxy+}
            Method: ANY
        RootResource:
          Type: Api
          Properties:
            Path: /userapi
            Method: ANY
      FunctionName: mcce22-smart-office-users
      Handler: Mcce22.SmartOffice.Users
      MemorySize: 256
      Policies:
        - AWSLambda_FullAccess
      Role: arn:aws:iam::064088109127:role/LabRole
      Runtime: dotnet6
      Timeout: 30

  Mcce22SmartOfficeWorkspacesLambda:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: ../Mcce22.SmartOffice.Workspaces/
        Events:
          ProxyResource:
            Type: Api
            Properties:
              Path: /workspaceapi/{proxy+}
              Method: ANY
          RootResource:
            Type: Api
            Properties:
              Path: /workspaceapi
              Method: ANY
        FunctionName: mcce22-smart-office-workspaces
        Handler: Mcce22.SmartOffice.Workspaces
        MemorySize: 256
        Policies:
          - AWSLambda_FullAccess
        Role: arn:aws:iam::064088109127:role/LabRole
        Runtime: dotnet6
        Timeout: 30

  Mcce22SmartOfficeBookingsLambda:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: ../Mcce22.SmartOffice.Bookings/
        Events:
          ProxyResource:
            Type: Api
            Properties:
              Path: /bookingapi/{proxy+}
              Method: ANY
          RootResource:
            Type: Api
            Properties:
              Path: /bookingapi
              Method: ANY
        FunctionName: mcce22-smart-office-bookings
        Handler: Mcce22.SmartOffice.Bookings
        MemorySize: 256
        Policies:
          - AWSLambda_FullAccess
        Role: arn:aws:iam::064088109127:role/LabRole
        Runtime: dotnet6
        Timeout: 30  