apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-depl
  namespace: default
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:latest
          imagePullPolicy: "Always"
          args: ["start-dev"]
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: gotohell
            - name: KC_PROXY
              value: edge
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KEYCLOAK_FRONTEND_URL
              value: http://localhost:8080/auth
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-clusterip-srv
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: keycloak
  ports:
    - name: keycloak
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
