apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webapp.appName }}-depl
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.webapp.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.webapp.appName }}
    spec:
      containers:
        - name: {{ .Values.webapp.appName }}
          image: {{ .Values.webapp.image }}
          imagePullPolicy: Always
          env:
          {{ if eq .Values.deployment "azure" }}
            - name: API_GATEWAY_BASE_URL
              value: 'https://{{ .Values.apiGateway.dnsLabel }}.westeurope.cloudapp.azure.com'
          {{ else if eq .Values.deployment "local"}}
            - name: API_GATEWAY_BASE_URL
              value: http://localhost:8080
          {{ end }}
            - name: KEYCLOAK_URL
              value: {{ .Values.authConfig.authUrl }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webapp.appName }}-clusterip-srv
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.webapp.appName }}
  ports:
    - name: {{ .Values.webapp.appName }}
      protocol: TCP
      port: 80
      targetPort: 8080
