apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: userimage-api-pv-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userimage-api-depl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userimage-api
  template:
    metadata:
      labels:
        app: userimage-api
    spec:
      containers:
        - name: userimage-api
          image: domih/mcce-smart-office-userimage-api:latest
          imagePullPolicy: Always
          env:
            - name: SMARTOFFICE_BASEADDRESS
              value: http://userimage-api-clusterip-srv:8080
            - name: SMARTOFFICE_STORAGEPATH
              value: /app/storage/userimages
            - name: SMARTOFFICE_FRONTENDURL
              value: "http://localhost:8081/userimage"
          envFrom:
            - configMapRef:
                name: env-configmap
          resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          volumeMounts:
            - name: userimage-api-storage
              mountPath: /app/storage
      volumes:
        - name: userimage-api-storage
          persistentVolumeClaim:
            claimName: userimage-api-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: userimage-api-clusterip-srv
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: userimage-api
  ports:
    - name: userimage-api
      protocol: TCP
      port: 80
      targetPort: 8080
