namespace: smartoffice

deployment: azure

configUrl: https://cfg-smartoffice-6z6i.azconfig.io

registryName: "acrsmartofficexlbt.azurecr.io"

resources:
  requests:
    memory: "128Mi"
    cpu: "125m"
  limits:
    memory: "512Mi"
    cpu: "250m"

accountApi:
  appName: account-api
  image:
    name: mcce-smart-office-account-api
    tag: latest

apiGateway:
  appName: apigateway
  dnsLabel: smartoffice-mcce22extreme
  image:
    name: mcce-smart-office-apigateway
    tag: latest

bookingApi:
  appName: booking-api
  image:
    name: mcce-smart-office-booking-api
    tag: latest

userimageApi:
  appName: userimage-api
  image:
    name: mcce-smart-office-userimage-api
    tag: latest
  shareName: userimages
  secretName: azure-secret

workspaceApi:
  appName: workspace-api
  image:
    name: mcce-smart-office-workspace-api
    tag: latest

workspaceconfigurationApi:
  appName: workspaceconfiguration-api
  image:
    name: mcce-smart-office-workspaceconfiguration-api
    tag: latest

workspacedataentryApi:
  appName: workspacedataentry-api
  image:
    name: mcce-smart-office-workspacedataentry-api
    tag: latest
